// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { WeakHands$Type } from "./WeakHands";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["WeakHands"]: WeakHands$Type;
    ["contracts/WeakHands.sol:WeakHands"]: WeakHands$Type;
  }

  interface ContractTypesMap {
    ["WeakHands"]: GetContractReturnType<WeakHands$Type["abi"]>;
    ["contracts/WeakHands.sol:WeakHands"]: GetContractReturnType<WeakHands$Type["abi"]>;
  }
}
