// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { MockV3Aggregator$Type } from "./MockV3Aggregator";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MockV3Aggregator"]: MockV3Aggregator$Type;
    ["contracts/MockV3Aggregator.sol:MockV3Aggregator"]: MockV3Aggregator$Type;
  }

  interface ContractTypesMap {
    ["MockV3Aggregator"]: GetContractReturnType<MockV3Aggregator$Type["abi"]>;
    ["contracts/MockV3Aggregator.sol:MockV3Aggregator"]: GetContractReturnType<MockV3Aggregator$Type["abi"]>;
  }
}
